// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShopBE.Web.API.Models;

#nullable disable

namespace ShopBE.Web.API.Migrations
{
    [DbContext(typeof(ShopDbContext))]
    [Migration("20231204125435_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CategorySanPham", b =>
                {
                    b.Property<int>("CategoryCATID")
                        .HasColumnType("int");

                    b.Property<int>("SanPhamMaSP")
                        .HasColumnType("int");

                    b.HasKey("CategoryCATID", "SanPhamMaSP");

                    b.HasIndex("SanPhamMaSP");

                    b.ToTable("CategorySanPham");
                });

            modelBuilder.Entity("ShopBE.Web.API.Models.CTHD", b =>
                {
                    b.Property<int>("SOHD")
                        .HasColumnType("int");

                    b.Property<int>("MASP")
                        .HasColumnType("int");

                    b.Property<int>("SL")
                        .HasColumnType("int");

                    b.HasKey("SOHD");

                    b.HasIndex("MASP");

                    b.ToTable("CTHD");
                });

            modelBuilder.Entity("ShopBE.Web.API.Models.Category", b =>
                {
                    b.Property<int>("CATID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CATID"));

                    b.Property<string>("CATNAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CATID");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("ShopBE.Web.API.Models.HoaDon", b =>
                {
                    b.Property<int>("SOHD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SOHD"));

                    b.Property<int>("MAKH")
                        .HasColumnType("int");

                    b.Property<int>("MANV")
                        .HasColumnType("int");

                    b.Property<DateTime>("NGHD")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TRIGIA")
                        .HasColumnType("decimal(8, 3)");

                    b.HasKey("SOHD");

                    b.HasIndex("MAKH");

                    b.HasIndex("MANV");

                    b.ToTable("HoaDon");
                });

            modelBuilder.Entity("ShopBE.Web.API.Models.KhachHang", b =>
                {
                    b.Property<int>("MAKH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MAKH"));

                    b.Property<string>("DCHI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DOANHSO")
                        .HasColumnType("decimal(8, 3)");

                    b.Property<string>("HOTEN")
                        .IsRequired()
                        .HasMaxLength(225)
                        .HasColumnType("nvarchar(225)");

                    b.Property<DateTime>("NGDK")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NGSINH")
                        .HasColumnType("datetime2");

                    b.Property<string>("SODT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MAKH");

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("ShopBE.Web.API.Models.NhanVien", b =>
                {
                    b.Property<int>("MANV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MANV"));

                    b.Property<string>("HOTEN")
                        .IsRequired()
                        .HasMaxLength(225)
                        .HasColumnType("nvarchar(225)");

                    b.Property<DateTime>("NGVL")
                        .HasColumnType("datetime2");

                    b.Property<string>("SODT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VITRI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MANV");

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("ShopBE.Web.API.Models.SanPham", b =>
                {
                    b.Property<int>("MaSP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSP"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(8, 3)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenSP")
                        .IsRequired()
                        .HasMaxLength(225)
                        .HasColumnType("nvarchar(225)");

                    b.HasKey("MaSP");

                    b.ToTable("SanPham");
                });

            modelBuilder.Entity("CategorySanPham", b =>
                {
                    b.HasOne("ShopBE.Web.API.Models.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryCATID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShopBE.Web.API.Models.SanPham", null)
                        .WithMany()
                        .HasForeignKey("SanPhamMaSP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShopBE.Web.API.Models.CTHD", b =>
                {
                    b.HasOne("ShopBE.Web.API.Models.SanPham", "SanPham")
                        .WithMany("CTHD")
                        .HasForeignKey("MASP")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShopBE.Web.API.Models.HoaDon", "HoaDon")
                        .WithMany("CTHD")
                        .HasForeignKey("SOHD")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HoaDon");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("ShopBE.Web.API.Models.HoaDon", b =>
                {
                    b.HasOne("ShopBE.Web.API.Models.KhachHang", "KhachHang")
                        .WithMany("HoaDon")
                        .HasForeignKey("MAKH")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShopBE.Web.API.Models.NhanVien", "NhanVien")
                        .WithMany("HoaDon")
                        .HasForeignKey("MANV")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("ShopBE.Web.API.Models.HoaDon", b =>
                {
                    b.Navigation("CTHD");
                });

            modelBuilder.Entity("ShopBE.Web.API.Models.KhachHang", b =>
                {
                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("ShopBE.Web.API.Models.NhanVien", b =>
                {
                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("ShopBE.Web.API.Models.SanPham", b =>
                {
                    b.Navigation("CTHD");
                });
#pragma warning restore 612, 618
        }
    }
}
